name: Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout whoami repo
        uses: actions/checkout@v4

      - name: Set commit and version vars
        id: vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "FULL_SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Clone ops repo
        uses: actions/checkout@v4
        with:
          repository: kosmonautas/whoami-ops
          token: ${{ secrets.OPS_REPO_TOKEN }}
          path: ops

      - name: Update values file for each team
        run: |
          ls -lah ops/helm/whoami/values/*
          for team in ops/helm/whoami/values/*; do
            values_file="$team/staging.yaml"
            if [ -f "$values_file" ]; then
              sed -i "s/^COMMIT: .*/COMMIT: \"${{ steps.vars.outputs.FULL_SHA }}\"/" "$values_file"
              sed -i -E "s/(WHOAMI_NAME: \".*-)[^\"]+/\1${{ steps.vars.outputs.SHORT_SHA }}/" "$values_file"
            else
              echo "no exist: $values_file"
            fi
          done

      - name: Commit and push
        run: |
          cd ops
          git status
          ls -lah
          git config user.name "bot"
          git config user.email "bot@github.com"
          git checkout -b update-staging-${{ steps.vars.outputs.SHORT_SHA }}
          git add .
          git commit -m "Update staging to version: ${{ steps.vars.outputs.SHORT_SHA }}"
          git push origin HEAD
